db.url=jdbc:postgresql://localhost:5432/weather_db
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
db.driver=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
weather.api.url=https://api.openweathermap.org/
weather.api.key=${OPENWEATHER_KEY}