db.url=${DB_URL:jdbc:postgresql://localhost:5432/weather_db}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
db.driver=org.postgresql.Driver
db.pool.maximumPoolSize=${DB_POOL_MAX_SIZE:10}
db.pool.minimumIdle=${DB_POOL_MIN_IDLE:5}
db.pool.connectionTimeout=${DB_POOL_CONN_TIMEOUT:30000}
db.pool.idleTimeout=${DB_POOL_IDLE_TIMEOUT:600000}
db.pool.maxLifetime=${DB_POOL_MAX_LIFETIME:1800000}
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=${SHOW_SQL:false}
hibernate.hbm2ddl.auto=none
thymeleaf.cache=true
weather.api.url=https://api.openweathermap.org/
weather.api.key=${OPENWEATHER_KEY}